RUNTIME ERROR: Unexpected type number, expected object
-------------------------------------------------
	testdata/builtinObjectHasExBadObject:1:1-32	builtin function <objectHasEx>

std.objectHasEx(42, "x", false)

-------------------------------------------------
	During evaluation	


