RUNTIME ERROR: xxx
-------------------------------------------------
	testdata/object_comp_err_elem:1:11-22	object <anonymous>

{ ["x"]:  error "xxx" for x in [1] }

-------------------------------------------------
	During manifestation	


