{ ["x"]:  error "xxx" for x in [1] }
